### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by baimiao666** [Xzavier0722/ClayTech#2]
** Describe 描述 **
NBT標籤不一樣 無法合成

** To Reproduce 如何复现 **
開啟指南就有

** Running Environment 运行环境 **
Minecraft Version: git-Paper-640 (MC: 1.16.5)
Slimefun Version: DEV - 936 (git aa5a22cb)
Plugin Version: ClayTech-violet-1.2.23.jar

** Screenshots 截图 **
https://imgur.com/bnFtYOw
https://imgur.com/Ho12gO1

**Comment by Xzavier0722** [comment]
经测试不影响使用，并非BUG
